import type { Metadata } from "next";
import { Roboto, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import NextTopLoader from "nextjs-toploader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin-ext"],
});

const quickSandFont = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${robotoFont.variable} ${quickSandFont.variable} antialiased`}
      >
        <Header />
        <main>
          {children}
          <NextTopLoader
            color="#21cdc0"
            height={4}
            showSpinner={true}
            zIndex={1600}
          />
        </main>
        <Footer />
      </body>
    </html>
  );
}
