import type { Metadata } from "next";
import { Roboto, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import NextTopLoader from "nextjs-toploader";
import UpScroll from "@/Components/Common/UpScroll";
import { Analytics } from "@vercel/analytics/next";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin-ext"],
});

const quickSandFont = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body
        className={`${robotoFont.variable} ${quickSandFont.variable} antialiased`}
      >
        <Header />
        <main>
          {children}
          <NextTopLoader
            color="#21cdc0"
            height={4}
            showSpinner={true}
            zIndex={1600}
          />
          <UpScroll />
        </main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
